---
- name: Desinstalar
  hosts: firebird
  become: yes
  tasks:
    - name: Desinstalar libncurses5
      apt:
        name: libncurses5
        state: absent

    - name: Desinstalar libtommath1
      apt:
        name: libtommath1
        state: absent

    - name: Desinstalar curl
      apt:
        name: curl
        state: absent

    - name: Desinstalar libicu-dev
      apt:
        name: libicu-dev
        state: absent        

    - name: Deletar Firebird
      ansible.builtin.shell: |
        rm -rf /tmp/Firebird-3.0.12.33787-0.amd64

    - name: Desinstalar Firebird
      ansible.builtin.shell:
        cmd: cd /opt/firebird/bin && yes 'masterkey' | /opt/firebird/bin/FirebirdUninstall.sh

    - name: Deletar security3_bkp.fdb
      ansible.builtin.shell:
        cmd: rm -rf /DATABASE/security3_bkp.fdb