---
- name: Gerenciar pacotes e atualizações por SO
  hosts: all
  become: yes
  tasks:
    - name: Atualizar cache e pacotes no Ubuntu
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts['distribution'] == "Ubuntu"
    
    - name: Criar diretório para banco de dados
      ansible.builtin.file:
        path: /DATABASE
        state: directory
        mode: '0777'
      when: ansible_facts['distribution'] == "Ubuntu"
    
    - name: Adicionar vm.max_map_count ao /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: "vm.max_map_count = 256000"
        state: present

    - name: Aplicar as alterações do sysctl
      ansible.builtin.command:
        cmd: sysctl -p /etc/sysctl.conf

    - name: Instalar libncurses5 libtommath1 curl tar libicu-dev
      ansible.builtin.apt:
        name:
          - libncurses5
          - libtommath1
          - libicu-dev
          - curl
          - tar
          - libicu-dev
        state: latest

    - name: Criar link simbólico
      ansible.builtin.shell: |
        TM=libtommath.so;
        for LIB in `find /lib* /usr/lib* -name ${TM}.1`;
        do ln -s ${TM}.1 `dirname ${LIB}`/${TM}.0;
        done;
        unset TM;
    
    - name: Download Firebird 3
      ansible.builtin.get_url:
        url: https://github.com/FirebirdSQL/firebird/releases/download/v3.0.12/Firebird-3.0.12.33787-0.amd64.tar.gz
        dest: /tmp/Firebird-3.0.12.33787-0.amd64.tar.gz

#    - name: Instalar Firebird